language: java

install: true

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env: WITH_COVERALLS=true
    - jdk: oraclejdk7
    - jdk: openjdk6

script:
 - if [ "$WITH_COVERALLS" == "true" ];
   then
     mvn -f com.examples.myproject/pom.xml clean verify -Pjacoco coveralls:report;
   else
    mvn -f com.examples.myproject/pom.xml clean verify;
   fi